// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjovjgxxazqmqsnqchqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqb3ZqZ3h4YXpxbXFzbnFjaHFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1OTEwNTcsImV4cCI6MjA3NDE2NzA1N30.L0gOcIcC4iwe1XLSZXMwdugkO8FqU5BUCs4t9HSooBc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});